### PR TITLE
HTTP GZip support for DroidFu BetterHttp

### PR DESCRIPTION
**Pull request by ysamlan**
Noticed there was no GZIP support in BetterHttp; I added it using the request/response-interceptor/ input-stream-wrapper style used by the Google I/O 2010 schedule app. Right now it's automatic, but if it causes problems for anyone it'd be easy enough to turn on/off with a flag, too.

### CODE REVIEW

**Comment by mttkay** [comment]
awesome thanks, was on our agenda anyway. will look into it soon.

**Comment by mttkay** [comment]
Great stuff, thanks, just two remarks:
- please only create pull requests from topic branches. Otherwise we have to merge this into our master, which means it will go untested into our app
- if you have local commits and want to pull back changes from upstream, please rebase the upstream master onto your local branch instead of merging it, because otherwise the commit history is full of merge commits that I have to pull back (just remember to never rebase commits that you had pushed before!)

we should be able to review, test, and pull back your changes this week. thanks again and keep it coming :-)

**Comment by ysamlan** [comment]
Got it - should I close this and create a new pull request using a new feature branch in my fork based off upstream/master that cherry-picks the relevant commit?

As far as the second point -- rebase upstream/master _onto_ my fork's branch (git rebase mybranch upstream/master) ? Won't that break the universe? Or did you mean the inverse (git rebase upstream/master mybranch, a la Diaspora's workflow: https://github.com/diaspora/diaspora/wiki/Git-Workflow)? And assuming you want me to rebase my fork's branch off of upstream/master, how can I do that without rebasing a pushed commit? (Not that it's the end of the world if I do that, since I'm the only one hacking on my own fork's branch).

**Comment by mttkay** [comment]
you're right of course. I meant rebasing your commits onto upstream/master. It's not required, but it'll get rid of all the "merge remote branch into ..." commits and make for a cleaner history. You do it by fetching from upstream, rebasing your master on ours, then pushing the result, then creating the pull request. From our perspective it then looks as if your changes are based on ours, even though they're not. Ex.: (assuming our remote is called upstream in your repo)

$git commit <your stuff>
$git fetch upstream
$git rebase upstream/master
$git push origin master

that way all commits have a common ancestor (the latest commit from our master) and no merge commits are required. When I said don't rebase commits that have been pushed, I meant that you must not do the rebase if you have already pushed your own commits to your own remote. For us it doesn't matter much, but your history will be fucked. That's because a rebase changes the SHAs of your commits, so if you push them, then rebase them, then we merge them back, and then you fetch again from us, then they will appear twice in your history.

Confusing stuff isn't it. :-)

PS: for this pull request don't bother changing it. was more a suggestion for future pull requests.

**Comment by ysamlan** [comment]
Got it. That's what I figured but I was just making sure I had that straight. Thanks!

**Comment by michaelengland** [comment]
Now pulled this to master, and made a few optimisations. Now, after calling BetterHttp.setupHttpClient(), you'll have to call BetterHttp.enableGZIPEncoding().

Good job! :)

**Pull request merged**
